
name: kurobako

on:
  pull_request: {}

jobs:
  hpobench-naval:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install gnuplot
      run: |
        sudo apt update
        sudo apt -y install gnuplot
    - name: Install Optuna
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Cache kurobako CLI
      id: cache-kurobako
      uses: actions/cache@v2
      with:
        path: ./kurobako
        key: kurobako-0-2-0
    - name: Download kurobako CLI
      if: steps.cache-kurobako.outputs.cache-hit != 'true'
      run: |
        curl -L https://github.com/sile/kurobako/releases/download/0.2.0/kurobako-0.2.0.linux-amd64 -o kurobako
        chmod +x kurobako
        ./kurobako -h
    - name: Cache hpobench dataset
      id: cache-hpobench-dataset
      uses: actions/cache@v2
      with:
        path: ./tmp/fcnet_tabular_benchmarks
        key: hpobench-dataset
    - name: Download hpobench dataset
      if: steps.cache-hpobench-dataset.outputs.cache-hit != 'true'
      run: |
        mkdir -p ./tmp
        wget -O ./tmp/fcnet_tabular_benchmarks.tar.gz http://ml4aad.org/wp-content/uploads/2019/01/fcnet_tabular_benchmarks.tar.gz
        tar xf ./tmp/fcnet_tabular_benchmarks.tar.gz -C ./tmp
    - name: Run Benchmark
      run: |
        kurobako solver random | tee solver.json
        kurobako problem hpobench ./fcnet_tabular_benchmarks/fcnet_naval_propulsion_data.hdf5 | tee problem.json
        kurobako studies --solvers $(cat solver.json) $(cat problem.json) | kurobako run > result.json
        cat result.json | kurobako report
        cat result.json | kurobako plot curve
